void foo() {
  try {
    throw Exception();
  } catch (e) {}
}
